In [42]:
#sort search & countingfunction

In [2]:
import numpy as np

In [3]:
arr = np.array([3,3,2,5,7,7,43,54,2]) 

In [4]:
arr

array([ 3,  3,  2,  5,  7,  7, 43, 54,  2])

In [8]:
np.sort(arr)

array([ 2,  2,  3,  3,  5,  7,  7, 43, 54])

In [10]:
np.searchsorted(arr,5)

3

In [14]:
arr1 = np.array([23,2,3,66,5,0,0,0,0,0,0,0,0,2,76,76,5454,7])

In [15]:
np.count_nonzero(arr1)

10

In [16]:
np.count_zero(arr1)

AttributeError: module 'numpy' has no attribute 'count_zero'

In [17]:
np.where(arr1 > 0)

(array([ 0,  1,  2,  3,  4, 13, 14, 15, 16, 17]),)

In [18]:
np.extract(arr1 > 2,arr1)

array([  23,    3,   66,    5,   76,   76, 5454,    7])

In [19]:
#numpy - byte swapping

In [20]:
arr1

array([  23,    2,    3,   66,    5,    0,    0,    0,    0,    0,    0,
          0,    0,    2,   76,   76, 5454,    7])

In [23]:
arr.byteswap()

array([ 216172782113783808,  216172782113783808,  144115188075855872,
        360287970189639680,  504403158265495552,  504403158265495552,
       3098476543630901248, 3891110078048108544,  144115188075855872])

In [24]:
arr

array([ 3,  3,  2,  5,  7,  7, 43, 54,  2])

In [25]:
arr1

array([  23,    2,    3,   66,    5,    0,    0,    0,    0,    0,    0,
          0,    0,    2,   76,   76, 5454,    7])

In [27]:
arr.byteswap(True)

array([ 216172782113783808,  216172782113783808,  144115188075855872,
        360287970189639680,  504403158265495552,  504403158265495552,
       3098476543630901248, 3891110078048108544,  144115188075855872])

In [28]:
#numpy copies and views

In [30]:
a= np.copy(arr1)

In [31]:
b= arr1.view()

In [32]:
b

array([  23,    2,    3,   66,    5,    0,    0,    0,    0,    0,    0,
          0,    0,    2,   76,   76, 5454,    7])

In [33]:
arr1

array([  23,    2,    3,   66,    5,    0,    0,    0,    0,    0,    0,
          0,    0,    2,   76,   76, 5454,    7])

In [34]:
#numpy - linear algebra

In [35]:
arr1 =np.random.randint([[2,3], [4,5]])

In [36]:
arr2=np.random.randint([[6,5], [2,5]])

In [37]:
arr1

array([[1, 2],
       [0, 4]])

In [38]:
arr2

array([[1, 4],
       [1, 0]])

In [40]:
np.dot(arr1,arr2)

array([[3, 4],
       [4, 0]])

In [41]:
arr1@arr2

array([[3, 4],
       [4, 0]])