In [8]:
import numpy as np

In [9]:
#Numpy - Array Manipulation.

In [16]:
arr =np.random.randint(1,10, [4,4])

In [17]:
arr

array([[5, 9, 2, 8],
       [8, 7, 8, 6],
       [5, 6, 8, 8],
       [9, 9, 4, 8]])

In [18]:
arr.reshape(8,2)

array([[5, 9],
       [2, 8],
       [8, 7],
       [8, 6],
       [5, 6],
       [8, 8],
       [9, 9],
       [4, 8]])

In [19]:
arr

array([[5, 9, 2, 8],
       [8, 7, 8, 6],
       [5, 6, 8, 8],
       [9, 9, 4, 8]])

In [20]:
arr.T

array([[5, 8, 5, 9],
       [9, 7, 6, 9],
       [2, 8, 8, 4],
       [8, 6, 8, 8]])

In [21]:
arr.flatten()

array([5, 9, 2, 8, 8, 7, 8, 6, 5, 6, 8, 8, 9, 9, 4, 8])

In [22]:
np.expand_dims(arr,axis=1)

array([[[5, 9, 2, 8]],

       [[8, 7, 8, 6]],

       [[5, 6, 8, 8]],

       [[9, 9, 4, 8]]])

In [23]:
np.expand_dims(arr,axis=0)

array([[[5, 9, 2, 8],
        [8, 7, 8, 6],
        [5, 6, 8, 8],
        [9, 9, 4, 8]]])

In [24]:
data = np.array([[1] , [2] , [3]])

In [25]:
np.squeeze(data)

array([1, 2, 3])

In [26]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [27]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [28]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [29]:
#Numpy - Binary Operators.

In [30]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [31]:
arr1

array([[1, 1, 2, 5],
       [9, 5, 1, 9],
       [2, 7, 6, 2]])

In [32]:
arr2

array([[6, 6, 2, 2],
       [2, 9, 4, 9],
       [1, 2, 2, 2]])

In [33]:
arr1+arr2

array([[ 7,  7,  4,  7],
       [11, 14,  5, 18],
       [ 3,  9,  8,  4]])

In [34]:
arr1*arr2

array([[ 6,  6,  4, 10],
       [18, 45,  4, 81],
       [ 2, 14, 12,  4]])

In [35]:
arr1**arr2

array([[        1,         1,         4,        25],
       [       81,   1953125,         1, 387420489],
       [        2,        49,        36,         4]])

In [36]:
~arr1

array([[ -2,  -2,  -3,  -6],
       [-10,  -6,  -2, -10],
       [ -3,  -8,  -7,  -3]])

In [37]:
arr1

array([[1, 1, 2, 5],
       [9, 5, 1, 9],
       [2, 7, 6, 2]])

In [38]:
arr1>arr2

array([[False, False, False,  True],
       [ True, False, False, False],
       [ True,  True,  True, False]])

In [39]:
#Numpy - String Functions.

In [40]:
arr = np.array(["sudh" , "kumar"])

In [41]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [42]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [43]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [44]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [45]:
#Numpy - Mathematical Functions.

In [46]:
arr1

array([[1, 1, 2, 5],
       [9, 5, 1, 9],
       [2, 7, 6, 2]])

In [47]:
np.sin(arr1)

array([[ 0.84147098,  0.84147098,  0.90929743, -0.95892427],
       [ 0.41211849, -0.95892427,  0.84147098,  0.41211849],
       [ 0.90929743,  0.6569866 , -0.2794155 ,  0.90929743]])

In [48]:
np.cos(arr1)

array([[ 0.54030231,  0.54030231, -0.41614684,  0.28366219],
       [-0.91113026,  0.28366219,  0.54030231, -0.91113026],
       [-0.41614684,  0.75390225,  0.96017029, -0.41614684]])

In [49]:
np.log10(arr1)

array([[0.        , 0.        , 0.30103   , 0.69897   ],
       [0.95424251, 0.69897   , 0.        , 0.95424251],
       [0.30103   , 0.84509804, 0.77815125, 0.30103   ]])

In [50]:
np.exp(arr1)

array([[2.71828183e+00, 2.71828183e+00, 7.38905610e+00, 1.48413159e+02],
       [8.10308393e+03, 1.48413159e+02, 2.71828183e+00, 8.10308393e+03],
       [7.38905610e+00, 1.09663316e+03, 4.03428793e+02, 7.38905610e+00]])

In [51]:
np.power(arr1,2)

array([[ 1,  1,  4, 25],
       [81, 25,  1, 81],
       [ 4, 49, 36,  4]])

In [52]:
np.mean(arr1
       )

4.166666666666667

In [53]:
np.median(arr1)

3.5

In [54]:
np.std(arr1)

2.939198681424733

In [55]:
np.var(arr1)

8.638888888888888

In [56]:
np.min(arr1)

1

In [57]:
np.max(arr1)

9

In [58]:
#Numpy - Arithmetic Operations.

In [59]:
arr1

array([[1, 1, 2, 5],
       [9, 5, 1, 9],
       [2, 7, 6, 2]])

In [60]:
arr2

array([[6, 6, 2, 2],
       [2, 9, 4, 9],
       [1, 2, 2, 2]])

In [61]:
arr1-arr2

array([[-5, -5,  0,  3],
       [ 7, -4, -3,  0],
       [ 1,  5,  4,  0]])

In [62]:
np.mod(arr1,arr2)

array([[1, 1, 0, 1],
       [1, 5, 1, 0],
       [0, 1, 0, 0]])

In [63]:
np.power(arr1,arr2)

array([[        1,         1,         4,        25],
       [       81,   1953125,         1, 387420489],
       [        2,        49,        36,         4]])

In [64]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356, 2.23606798],
       [3.        , 2.23606798, 1.        , 3.        ],
       [1.41421356, 2.64575131, 2.44948974, 1.41421356]])

In [65]:
#Numpy - Statistical Functions.

In [66]:
arr1

array([[1, 1, 2, 5],
       [9, 5, 1, 9],
       [2, 7, 6, 2]])

In [67]:
np.mean(arr1)

4.166666666666667

In [68]:
np.std(arr1)

2.939198681424733

In [69]:
np.median(arr1)

3.5