In [1]:
import numpy as np

In [2]:
list(range (5))

[0, 1, 2, 3, 4]

In [3]:
list(range (0,5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
#error bcoz it is point its not integer value 


In [7]:
list(np.arange(.4 , 10.10))

[0.4,
 1.4,
 2.4,
 3.3999999999999995,
 4.3999999999999995,
 5.3999999999999995,
 6.3999999999999995,
 7.3999999999999995,
 8.399999999999999,
 9.399999999999999]

In [17]:
np.linspace(2 , 10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [18]:
np.logspace(2 , 10, base=2)

array([   4.        ,    4.4792752 ,    5.01597658,    5.61698488,
          6.29000526,    7.04366615,    7.88762977,    8.83271611,
          9.89104156,   11.07617429,   12.4033082 ,   13.88945771,
         15.55367586,   17.41729864,   19.50421847,   21.84119052,
         24.45817576,   27.38872504,   30.67040921,   34.34530084,
         38.46051358,   43.06880616,   48.22925884,   54.00803077,
         60.47920821,   67.72575437,   75.840573  ,   84.92769946,
         95.1036345 ,  106.49883788,  119.25940085,  133.54891916,
        149.55059042,  167.46956272,  187.53556478,  210.00585114,
        235.16850024,  263.34610777,  294.89992242,  330.23447729,
        369.80277612,  414.11210104,  463.7305161 ,  519.29415013,
        581.51535211,  651.19182386,  729.21684685,  816.59073448,
        914.43365648, 1024.        ])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros((5,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
np.zeros((2,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [29]:
np.ones(3)

array([1., 1., 1.])

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
arr=np.ones((3,4))

In [35]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [37]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [41]:
np.eye(5)     #diagonal matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
arr1=np.eye(5) 

In [43]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
import pandas as pd

In [46]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [47]:
np.random.rand(2,3)

array([[0.27597152, 0.92807868, 0.46063032],
       [0.99514383, 0.71674541, 0.35722461]])

In [48]:
np.random.randn(2,3)

array([[-0.71536744,  0.7020097 ,  0.24548981],
       [ 1.33150854, -0.01493251, -1.49540692]])

In [49]:
np.random.randint(1,5 , (3,4))

array([[2, 2, 4, 3],
       [2, 1, 3, 2],
       [2, 1, 4, 1]])

In [50]:
arr2=np.random.randint(1,5 , (3,4))

In [51]:
arr2

array([[1, 1, 2, 2],
       [4, 3, 4, 4],
       [1, 3, 1, 1]])

In [52]:
arr2.size

12

In [53]:
arr2.shape

(3, 4)

In [54]:
arr2.reshape(6,2)

array([[1, 1],
       [2, 2],
       [4, 3],
       [4, 4],
       [1, 3],
       [1, 1]])

In [55]:
arr2.reshape(2,6)

array([[1, 1, 2, 2, 4, 3],
       [4, 4, 1, 3, 1, 1]])

In [56]:
arr2.reshape(4,3)

array([[1, 1, 2],
       [2, 4, 3],
       [4, 4, 1],
       [3, 1, 1]])

In [57]:
arr2.reshape(4,-1)

array([[1, 1, 2],
       [2, 4, 3],
       [4, 4, 1],
       [3, 1, 1]])

In [58]:
arr2.reshape(4,-1432453453)

array([[1, 1, 2],
       [2, 4, 3],
       [4, 4, 1],
       [3, 1, 1]])

In [59]:
arr1 = np.random.randint(1,10 , (5,6))

In [60]:
arr1

array([[8, 4, 3, 6, 6, 6],
       [2, 4, 2, 6, 6, 5],
       [8, 4, 9, 9, 1, 8],
       [9, 7, 4, 1, 5, 5],
       [6, 9, 5, 3, 9, 7]])

In [61]:
arr1 >8

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True,  True, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False, False,  True, False]])

In [62]:
arr1[arr1 >8]

array([9, 9, 9, 9, 9])

In [63]:
arr1

array([[8, 4, 3, 6, 6, 6],
       [2, 4, 2, 6, 6, 5],
       [8, 4, 9, 9, 1, 8],
       [9, 7, 4, 1, 5, 5],
       [6, 9, 5, 3, 9, 7]])

In [64]:
arr1[0,[0,1]]

array([8, 4])

In [65]:
arr1[2:4 , [2,3]]

array([[9, 9],
       [4, 1]])

In [66]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [67]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [68]:
arr2

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [69]:
arr1+arr2

array([[3, 2, 4],
       [4, 2, 4],
       [4, 3, 3]])

In [70]:
arr1-arr2

array([[-1,  0,  0],
       [ 0,  0,  0],
       [ 0,  1, -1]])

In [71]:
arr1*arr2

array([[2, 1, 4],
       [4, 1, 4],
       [4, 2, 2]])

In [72]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [73]:
arr2

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [74]:
arr1@arr2

array([[ 8,  4,  8],
       [10,  5, 10],
       [10,  5, 10]])

In [75]:
arr1/arr2

array([[0.5, 1. , 1. ],
       [1. , 1. , 1. ],
       [1. , 2. , 0.5]])

In [76]:
arr1/0

/var/folders/fd/hfyxn16n77v2xc3jhkw_7pjc0000gn/T/ipykernel_17271/1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [77]:
#Numpy – Broadcasting.

In [78]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
arr=np.zeros((3,4))

In [80]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [84]:
a = np.array([1,2,3,4])

In [85]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [86]:
b = np.array([[3,4,5]])

In [87]:
arr1 = arr+b.T

In [88]:
b.T

array([[3],
       [4],
       [5]])

In [89]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [90]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [91]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [92]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [93]:
np.min(arr1)

3.0

In [94]:
np.max(arr1)

5.0