In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5,6] 

In [4]:
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [7]:
np.array([[1,2,3], [2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
arr1 = np.array([[1,2,3], [2,3,4]])

In [9]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
arr.ndim

1

In [11]:
arr1.ndim

2

In [12]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5, 6]])

In [13]:
mat =np.matrix(l)

In [14]:
mat

matrix([[1, 2, 3, 4, 5, 6]])

In [16]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

In [17]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5, 6]])

In [18]:
arr

array([1, 2, 3, 4, 5, 6])

In [19]:
arr[0] = 100

In [20]:
arr

array([100,   2,   3,   4,   5,   6])

In [21]:
arr[2]= 21

In [22]:
arr

array([100,   2,  21,   4,   5,   6])

In [23]:
b= np.copy(arr)

In [24]:
b

array([100,   2,  21,   4,   5,   6])

In [25]:
b[0] = 1

In [26]:
b

array([ 1,  2, 21,  4,  5,  6])

In [28]:
arr        #in this it will not show effect on array

array([100,   2,  21,   4,   5,   6])

In [32]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [35]:
list(i*i for i in range (5))

[0, 1, 4, 9, 16]

In [36]:
iterable = list(i*i for i in range (5))

In [37]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [41]:
np.fromstring('3 2 3', sep= ' ')

array([3., 2., 3.])

In [43]:
np.fromstring('3,4, 5', sep =',')

array([3., 4., 5.])

In [44]:
arr

array([100,   2,  21,   4,   5,   6])

In [45]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [46]:
arr.ndim

1

In [47]:
arr.size

6

In [48]:
arr1.size

6

In [49]:
arr1.shape

(2, 3)

In [53]:
arr.dtype

dtype('int64')

In [54]:
arr1.dtype

dtype('int64')